---


- name: Add apt-key
  apt_key: 
    id: "0C49F3730359A14518585931BC711F9BA15703C6"
#    id: "7F0CEB10"
    keyserver: "{{ key_server }}"
    state: present

- name: Add mongodb repo
  command: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
#  apt_repository:
#    repo: deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
#    state: present


# - name: update and upgrade apt packages
#   command: sudo apt-get update
#   apt: 
#     upgrade: dist
#     update_cache: yes
#     cache_valid_time: 3600


# - name: Install MongoDB
#   apt:
#     pkg: mongodb-org
#     state: present


# - name: Install mongo
#   apt: name=mongodb-org state=latest update_cache=yes


- name: Install mongo
  command: sudo apt-get install mongodb-org -y


- name: start MongoDB
  service:
    name: mongod
    state: started
    notify:
    - restart mongod
